### ISSUE TITLE
Installation error with composer

### ISSUE THREAD

**Issue by ezimuel** [Roave/BackwardCompatibilityCheck#183]
I tried to install the library using composer with the command reported in the README.md:
```bash
composer require --dev roave/backward-compatibility-check
```
But I got this dependency error:
```
Problem 1
    - Can only install one of: phpdocumentor/type-resolver[1.0.1, 0.4.0].
    - Can only install one of: phpdocumentor/type-resolver[0.4.0, 1.0.1].
    - Can only install one of: phpdocumentor/type-resolver[0.4.0, 1.0.1].
    - roave/better-reflection 3.5.0 requires phpdocumentor/type-resolver ^0.4.0 -> satisfiable by phpdocumentor/type-resolver[0.4.0].
    - roave/backward-compatibility-check 4.2.0 requires roave/better-reflection ^3.5.0 -> satisfiable by roave/better-reflection[3.5.0].
    - Installation request for roave/backward-compatibility-check ^4.2 -> satisfiable by roave/backward-compatibility-check[4.2.0].
    - Installation request for phpdocumentor/type-resolver (locked at 1.0.1) -> satisfiable by phpdocumentor/type-resolver[1.0.1].
```
My `composer.json` is the one reported [here](https://github.com/elastic/elasticsearch-php/blob/master/composer.json).

**Comment by Ocramius** [comment]
`roave/better-reflection 3.5.0 requires phpdocumentor/type-resolver ^0.4.0` seems to be the culprit (`0.4.0` is locked due to `composer require` only working on a specific subset of dependencies).

Couple of things to try:

 1. help `roave/better-reflection` in moving to `phpdocumentor/type-resolver:1.0.1`
 2. don't use `composer require`, which leads to locked dependencies, but rather add the dependency to `composer.json` manually, then run `composer update` to allow it to run with unlocked dependencies.

**Comment by ezimuel** [comment]
I tried using `phpdocumentor/type-resolver:1.0.1` but still having the error dependency.
When I moved to `phpdocumentor/type-resolver:^0.4.0` everything worked fine.

My `compose.json` looks as follows:

```php
"require-dev": {
    ...
    "phpdocumentor/type-resolver": "^0.4.0",
    "roave/backward-compatibility-check": "^4.2"
  },
```

**Comment by Ocramius** [comment]
> I tried using `phpdocumentor/type-resolver:1.0.1` but still having the error dependency.

The idea is that `roave/better-reflection` needs to be updated to that ;-)

**Comment by ezimuel** [comment]
I see, thanks for your support!
