### ISSUE TITLE
`laminas/automatic-releases` roll out

### ISSUE THREAD

**Issue by asgrim** [Roave/BackwardCompatibilityCheck#265]
It would be nice to move onto using `laminas/automatic-releases`, but there is a key issue in that the PHAR releases may be broken since the release workflow isn't triggered as I understand it.

**Comment by Ocramius** [comment]
Introducing automatic releaaes won't be an issue. The PHAR generation scripts don't seem to work at the moment though.

**Comment by tomasnorre** [comment]
Can I help out here? Would like to get to know the `laminas/automatic-releases` better to see if it's could be beneficial for my repository.

**Comment by Ocramius** [comment]
It could be (in theory) copied from `roave/better-reflection` (literally copy the `yml` file over).

The reason why this isn't done yet is due to phar builds, which are regularly broken, and tbh I don't see as a priority for now.

If you think there's a chance to automate also phar builds with it (as a reaction to releases - separate workflow), then by all means go for it 👍

**Comment by tomasnorre** [comment]
I'll have a look at it and see what I can come up with.
