### ISSUE TITLE
Support BetterReflection ^4.0 too

### ISSUE THREAD

**Issue by asgrim** [Roave/BackwardCompatibilityCheck#90]
See Roave/BetterReflection#441

At the moment this won't be an issue for any other consumer, except BR because BR `master` is on `4.0-dev` now, but we only support `^3.0` in BackwardCompatibilityCheck.

Need to check what the changes are (so far) in BR 3->4 and figure out if we can support both.

**Comment by Ocramius** [comment]
Gonna defer this for now, but I think it should be solved in `Roave/BetterReflection` by checking out the branch as `3.0` when running against `roave/backward-compatibility-check`

**Comment by Ocramius** [comment]
As noted in https://github.com/Roave/BetterReflection/issues/441#issuecomment-485774052, we shouldn't change dependency constraints downstream: since this is only a build dependency for upstream, we should be OK with having upstream hack its way into either tagging or renaming itself during the build (for testing purposes)
